### ISSUE TITLE
导入组件内容错误

### ISSUE THREAD

**Issue by dshuais** [uni-helper/vite-plugin-uni-components#10]
### 描述问题

使用自动导入导入了一个components/Test/TestPop组件，uni-components.d.ts内生成正常，在页面内使用时，TestPop组件内容被替换为当前页面内容？？
![image](https://github.com/user-attachments/assets/5d67030a-f9d5-4f75-bec3-3d2f4dc6a107)
![image](https://github.com/user-attachments/assets/97bbf2da-5591-4d39-8f58-4370af189cf8)
![image](https://github.com/user-attachments/assets/dd7dbde0-4e63-4502-b041-6137be331d49)
![image](https://github.com/user-attachments/assets/174b8865-14c4-4327-a024-88e2e4ebb517)

### 复现

我没有单独测试demo，可以在我的仓库内查看，我正在使用你们的工具搭建一个自用模板

地址：https://github.com/dshuais/uni3-template

### 系统信息

create-uni@1.4.13

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by dshuais** [comment]
补充，根据文档使用pnpm时在.npmrc文件内 新增了shamefully-hoist=true

**Comment by dshuais** [comment]
上面的问题已经解决，卸载又下载后发现没有问题了。
但是又发现了另一个问题，就是当前自动导入的组件并没有类型推断，也就是说`uni-components.d.ts`文件并没有生效

通过排查发现，可能是因为我使用了`pinia`，所以发现好像是这里冲突了
![image](https://github.com/user-attachments/assets/3c940112-def4-490b-83ac-c8a74265cd98)

我尝试修改`uni-components.d.ts`文件的`'@vue/runtime-core'`为`'vue'`，果然 它生效了。

这个问题一般是怎么解决呢？需要固定具体的`pinia`的版本吗

**Comment by ModyQyW** [comment]
Please try v0.1.0
