### ISSUE TITLE
最新版 volar在组件中无法获得类型

### ISSUE THREAD

**Issue by yang1206** [uni-helper/vite-plugin-uni-components#5]
### 描述问题

`volar 1.65`

![](https://s2.loli.net/2023/07/02/4DhiyklvMPXq1Ew.png)

`volar 1.83`

![](https://s2.loli.net/2023/07/02/OmEVUsGW8fSzLRb.png)

生成的类型文件实际上都有类型

![](https://s2.loli.net/2023/07/02/WIbZ9Ey6xXo1kc8.png)

### 复现

https://github.com/yang1206/vitesse-uni-app

### 系统信息

```Shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 68.67 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.volta/tools/image/node/18.15.0/bin/node
    Yarn: 1.0.0 - ~/.volta/tools/image/yarn/1.0.0/bin/yarn
    npm: 9.5.0 - ~/.volta/tools/image/node/18.15.0/bin/npm
    pnpm: 8.6.1 - ~/.volta/bin/pnpm
    Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1

vscode: 1.79.2
volar: 1.83
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ljhmp** [comment]
> ### 描述问题
> `volar 1.65`
> 
> ![](https://camo.githubusercontent.com/74a6e365d6855ece7f7fd74ff4c601e0a4548db8dd5171c8fbf63246b2787b15/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30372f30322f34446869796b6c764d5058713145772e706e67)
> 
> `volar 1.83`
> 
> ![](https://camo.githubusercontent.com/01dd8857dd79a2fdc8eeccd74eb3b6368dfbe6fccd025b54be480839a237ba87/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30372f30322f4f6d4556557347573866537a4c52622e706e67)
> 
> 生成的类型文件实际上都有类型
> 
> ![](https://camo.githubusercontent.com/5b6db5b5f81c0784dcb0424cfd17951f31a1f26d1b06444c3e8f196148e44782/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30372f30322f5749625a3945793678586f316b63382e706e67)
> 
> ### 复现
> https://github.com/yang1206/vitesse-uni-app
> 
> ### 系统信息
> ```shell
> System:
>     OS: macOS 13.4.1
>     CPU: (8) arm64 Apple M1 Pro
>     Memory: 68.67 MB / 16.00 GB
>     Shell: 5.9 - /bin/zsh
>   Binaries:
>     Node: 18.15.0 - ~/.volta/tools/image/node/18.15.0/bin/node
>     Yarn: 1.0.0 - ~/.volta/tools/image/yarn/1.0.0/bin/yarn
>     npm: 9.5.0 - ~/.volta/tools/image/node/18.15.0/bin/npm
>     pnpm: 8.6.1 - ~/.volta/bin/pnpm
>     Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
>   Browsers:
>     Chrome: 114.0.5735.198
>     Safari: 16.5.1
> 
> vscode: 1.79.2
> volar: 1.83
> ```
> 
> ### 使用的包管理器
> pnpm
> 
> ### 核对
> * [x]  遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
> * [x]  检查是否已经有一个报告相同错误的问题，以避免重复创建。
> * [x]  这是一个具体的错误。请开启 GitHub 讨论你的疑问。
> * [x]  所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。



> ### 描述问题
> `volar 1.65`
> 
> ![](https://camo.githubusercontent.com/74a6e365d6855ece7f7fd74ff4c601e0a4548db8dd5171c8fbf63246b2787b15/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30372f30322f34446869796b6c764d5058713145772e706e67)
> 
> `volar 1.83`
> 
> ![](https://camo.githubusercontent.com/01dd8857dd79a2fdc8eeccd74eb3b6368dfbe6fccd025b54be480839a237ba87/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30372f30322f4f6d4556557347573866537a4c52622e706e67)
> 
> 生成的类型文件实际上都有类型
> 
> ![](https://camo.githubusercontent.com/5b6db5b5f81c0784dcb0424cfd17951f31a1f26d1b06444c3e8f196148e44782/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30372f30322f5749625a3945793678586f316b63382e706e67)
> 
> ### 复现
> https://github.com/yang1206/vitesse-uni-app
> 
> ### 系统信息
> ```shell
> System:
>     OS: macOS 13.4.1
>     CPU: (8) arm64 Apple M1 Pro
>     Memory: 68.67 MB / 16.00 GB
>     Shell: 5.9 - /bin/zsh
>   Binaries:
>     Node: 18.15.0 - ~/.volta/tools/image/node/18.15.0/bin/node
>     Yarn: 1.0.0 - ~/.volta/tools/image/yarn/1.0.0/bin/yarn
>     npm: 9.5.0 - ~/.volta/tools/image/node/18.15.0/bin/npm
>     pnpm: 8.6.1 - ~/.volta/bin/pnpm
>     Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
>   Browsers:
>     Chrome: 114.0.5735.198
>     Safari: 16.5.1
> 
> vscode: 1.79.2
> volar: 1.83
> ```
> 
> ### 使用的包管理器
> pnpm
> 
> ### 核对
> * [x]  遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
> * [x]  检查是否已经有一个报告相同错误的问题，以避免重复创建。
> * [x]  这是一个具体的错误。请开启 GitHub 讨论你的疑问。
> * [x]  所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

尝试修改你的tsconfig.json文件，在include配置下添加："./node_modules/uniapp-nutui/components/**/*.vue"
`"include": [
    ...,
    "./node_modules/uniapp-nutui/components/**/*.vue"
  ]`

**Comment by yang1206** [comment]
> > ### 描述问题
> 
> > `volar 1.65`
> 
> > 
> 
> > ![](https://camo.githubusercontent.com/74a6e365d6855ece7f7fd74ff4c601e0a4548db8dd5171c8fbf63246b2787b15/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30372f30322f34446869796b6c764d5058713145772e706e67)
> 
> > 
> 
> > `volar 1.83`
> 
> > 
> 
> > ![](https://camo.githubusercontent.com/01dd8857dd79a2fdc8eeccd74eb3b6368dfbe6fccd025b54be480839a237ba87/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30372f30322f4f6d4556557347573866537a4c52622e706e67)
> 
> > 
> 
> > 生成的类型文件实际上都有类型
> 
> > 
> 
> > ![](https://camo.githubusercontent.com/5b6db5b5f81c0784dcb0424cfd17951f31a1f26d1b06444c3e8f196148e44782/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30372f30322f5749625a3945793678586f316b63382e706e67)
> 
> > 
> 
> > ### 复现
> 
> > https://github.com/yang1206/vitesse-uni-app
> 
> > 
> 
> > ### 系统信息
> 
> > ```shell
> 
> > System:
> 
> >     OS: macOS 13.4.1
> 
> >     CPU: (8) arm64 Apple M1 Pro
> 
> >     Memory: 68.67 MB / 16.00 GB
> 
> >     Shell: 5.9 - /bin/zsh
> 
> >   Binaries:
> 
> >     Node: 18.15.0 - ~/.volta/tools/image/node/18.15.0/bin/node
> 
> >     Yarn: 1.0.0 - ~/.volta/tools/image/yarn/1.0.0/bin/yarn
> 
> >     npm: 9.5.0 - ~/.volta/tools/image/node/18.15.0/bin/npm
> 
> >     pnpm: 8.6.1 - ~/.volta/bin/pnpm
> 
> >     Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
> 
> >   Browsers:
> 
> >     Chrome: 114.0.5735.198
> 
> >     Safari: 16.5.1
> 
> > 
> 
> > vscode: 1.79.2
> 
> > volar: 1.83
> 
> > ```
> 
> > 
> 
> > ### 使用的包管理器
> 
> > pnpm
> 
> > 
> 
> > ### 核对
> 
> > * [x]  遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
> 
> > * [x]  检查是否已经有一个报告相同错误的问题，以避免重复创建。
> 
> > * [x]  这是一个具体的错误。请开启 GitHub 讨论你的疑问。
> 
> > * [x]  所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。
> 
> 
> 
> 
> 
> 
> 
> > ### 描述问题
> 
> > `volar 1.65`
> 
> > 
> 
> > ![](https://camo.githubusercontent.com/74a6e365d6855ece7f7fd74ff4c601e0a4548db8dd5171c8fbf63246b2787b15/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30372f30322f34446869796b6c764d5058713145772e706e67)
> 
> > 
> 
> > `volar 1.83`
> 
> > 
> 
> > ![](https://camo.githubusercontent.com/01dd8857dd79a2fdc8eeccd74eb3b6368dfbe6fccd025b54be480839a237ba87/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30372f30322f4f6d4556557347573866537a4c52622e706e67)
> 
> > 
> 
> > 生成的类型文件实际上都有类型
> 
> > 
> 
> > ![](https://camo.githubusercontent.com/5b6db5b5f81c0784dcb0424cfd17951f31a1f26d1b06444c3e8f196148e44782/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30372f30322f5749625a3945793678586f316b63382e706e67)
> 
> > 
> 
> > ### 复现
> 
> > https://github.com/yang1206/vitesse-uni-app
> 
> > 
> 
> > ### 系统信息
> 
> > ```shell
> 
> > System:
> 
> >     OS: macOS 13.4.1
> 
> >     CPU: (8) arm64 Apple M1 Pro
> 
> >     Memory: 68.67 MB / 16.00 GB
> 
> >     Shell: 5.9 - /bin/zsh
> 
> >   Binaries:
> 
> >     Node: 18.15.0 - ~/.volta/tools/image/node/18.15.0/bin/node
> 
> >     Yarn: 1.0.0 - ~/.volta/tools/image/yarn/1.0.0/bin/yarn
> 
> >     npm: 9.5.0 - ~/.volta/tools/image/node/18.15.0/bin/npm
> 
> >     pnpm: 8.6.1 - ~/.volta/bin/pnpm
> 
> >     Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
> 
> >   Browsers:
> 
> >     Chrome: 114.0.5735.198
> 
> >     Safari: 16.5.1
> 
> > 
> 
> > vscode: 1.79.2
> 
> > volar: 1.83
> 
> > ```
> 
> > 
> 
> > ### 使用的包管理器
> 
> > pnpm
> 
> > 
> 
> > ### 核对
> 
> > * [x]  遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
> 
> > * [x]  检查是否已经有一个报告相同错误的问题，以避免重复创建。
> 
> > * [x]  这是一个具体的错误。请开启 GitHub 讨论你的疑问。
> 
> > * [x]  所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。
> 
> 
> 
> 尝试修改你的tsconfig.json文件，在include配置下添加："./node_modules/uniapp-nutui/components/**/*.vue"
> 
> `"include": [
> 
>     ...,
> 
>     "./node_modules/uniapp-nutui/components/**/*.vue"
> 
>   ]`

实际上是 volar 的问题

https://github.com/vuejs/language-tools/issues/3388

**Comment by yang1206** [comment]
测试 volar 1.88已修复
