### ISSUE TITLE
使用Vant的自动导入时会生成default属性导致无法导入

### ISSUE THREAD

**Issue by censujiang** [uni-helper/vite-plugin-uni-components#7]
### 描述问题

使用vant的自动导入功能会生成default属性，最终使得组件不能被自动倒入。

我看文档的意思是所有自动导入都会生成为Default属性，个人建议加一个排除开关

### 复现

无

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 4.88 GB / 23.88 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (118.0.2088.69)
    Internet Explorer: 11.0.19041.3570
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by zguolee** [comment]
Vant 组件是使用的H5版本？如果是这样就没必要用这个库了，直接使用`unplugin-vue-components`

**Comment by censujiang** [comment]
fixed
